table Table1
	lineageTag: 524ebea9-91f1-4c8f-9b48-bb564456be70

	column 'Item Fat Content'
		dataType: string
		lineageTag: 58e1d687-024f-41a0-a593-1667ead18e7f
		summarizeBy: none
		sourceColumn: Item Fat Content

		annotation SummarizationSetBy = Automatic

	column 'Item Identifier'
		dataType: string
		lineageTag: 941d4430-0371-40ee-be34-1ea38144be44
		summarizeBy: none
		sourceColumn: Item Identifier

		annotation SummarizationSetBy = Automatic

	column 'Item Type'
		dataType: string
		lineageTag: 5dc06afa-657b-4f06-b27f-ac91f2262566
		summarizeBy: none
		sourceColumn: Item Type

		annotation SummarizationSetBy = Automatic

	column 'Outlet Establishment Year'
		dataType: int64
		formatString: 0
		lineageTag: 556d35a3-5a2a-4539-8924-bf643bf671ca
		summarizeBy: sum
		sourceColumn: Outlet Establishment Year

		annotation SummarizationSetBy = Automatic

	column 'Outlet Identifier'
		dataType: string
		lineageTag: 033a03db-00d8-42f0-b58a-ef4bb5aec22a
		summarizeBy: none
		sourceColumn: Outlet Identifier

		annotation SummarizationSetBy = Automatic

	column 'Outlet Location Type'
		dataType: string
		lineageTag: ad5a7009-fac7-4e0a-886b-2f6c835ba438
		summarizeBy: none
		sourceColumn: Outlet Location Type

		annotation SummarizationSetBy = Automatic

	column 'Outlet Size'
		dataType: string
		lineageTag: 2cc5df34-46e0-4af2-8043-5910317a3853
		summarizeBy: none
		sourceColumn: Outlet Size

		annotation SummarizationSetBy = Automatic

	column 'Outlet Type'
		dataType: string
		lineageTag: 2cedd419-589a-4d24-b803-39556f81dd64
		summarizeBy: none
		sourceColumn: Outlet Type

		annotation SummarizationSetBy = Automatic

	column 'Item Visibility'
		dataType: double
		lineageTag: 370bf289-6dcf-4415-91a5-71880243a499
		summarizeBy: sum
		sourceColumn: Item Visibility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Weight'
		dataType: double
		lineageTag: a4144546-7eae-4f8e-9327-3f4cfb1db6fe
		summarizeBy: sum
		sourceColumn: Item Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: dbd0e69d-9788-4133-9512-860fdc385f6a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: 92c37664-194b-4268-b722-c15e3e47022b
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	partition Table1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\shash\Downloads\BlinkIT Grocery Data.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Item Fat Content", type text}, {"Item Identifier", type text}, {"Item Type", type text}, {"Outlet Establishment Year", Int64.Type}, {"Outlet Identifier", type text}, {"Outlet Location Type", type text}, {"Outlet Size", type text}, {"Outlet Type", type text}, {"Item Visibility", type number}, {"Item Weight", type number}, {"Sales", type number}, {"Rating", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

