table zomato_restaurants_in_India
	lineageTag: ba35dcfc-68f3-4f65-b2d2-8ca6480ac398

	column res_id
		dataType: int64
		formatString: 0
		lineageTag: caf5b76f-87f5-4303-bf1d-0ce00a23b987
		summarizeBy: sum
		sourceColumn: res_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ae8df7a2-27de-4a5f-9d48-967890ed76d7
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column establishment
		dataType: string
		lineageTag: 7e910ed8-cae4-4e36-a6de-544ec390e22e
		summarizeBy: none
		sourceColumn: establishment

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 0514c2ef-2da4-4159-a92a-37c75b6af1d3
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: cafd4a2b-fb58-4246-80e9-c67764ddc244
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 6aab763f-3f0d-46a8-aad6-e0e5e9010469
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column city_id
		dataType: int64
		formatString: 0
		lineageTag: 3f886264-b6e9-4b1a-9b0a-7c0e102996ce
		summarizeBy: sum
		sourceColumn: city_id

		annotation SummarizationSetBy = Automatic

	column locality
		dataType: string
		lineageTag: f4f80bde-7a71-4811-82dc-e8ded590ef3b
		summarizeBy: none
		sourceColumn: locality

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: e780ce76-0049-4c17-b68d-3d48bcfde857
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: cdb07633-1426-47dc-b11e-b8fe82127276
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zipcode
		dataType: int64
		formatString: 0
		lineageTag: cd35fa02-2985-4172-aa50-e2f66639893b
		summarizeBy: sum
		sourceColumn: zipcode

		annotation SummarizationSetBy = Automatic

	column country_id
		dataType: int64
		formatString: 0
		lineageTag: dc28501c-dd8b-4fdc-8dcd-d81f3a65d991
		summarizeBy: sum
		sourceColumn: country_id

		annotation SummarizationSetBy = Automatic

	column locality_verbose
		dataType: string
		lineageTag: ccdc3009-5f19-4e92-9375-84a939f74b99
		summarizeBy: none
		sourceColumn: locality_verbose

		annotation SummarizationSetBy = Automatic

	column cuisines
		dataType: string
		lineageTag: f19f76ea-1366-4d0b-aad8-44d5733876fe
		summarizeBy: none
		sourceColumn: cuisines

		annotation SummarizationSetBy = Automatic

	column timings
		dataType: string
		lineageTag: 8c55ba1e-0689-4114-94bf-cc00cd990e8f
		summarizeBy: none
		sourceColumn: timings

		annotation SummarizationSetBy = Automatic

	column average_cost_for_two
		dataType: int64
		formatString: 0
		lineageTag: d4803b41-d6c3-4cc3-97da-32bf5da155ef
		summarizeBy: sum
		sourceColumn: average_cost_for_two

		annotation SummarizationSetBy = Automatic

	column price_range
		dataType: int64
		formatString: 0
		lineageTag: 3ace2547-6da1-4f60-b369-11ab3a235893
		summarizeBy: sum
		sourceColumn: price_range

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 6dccdd61-b7a1-4c8f-a300-e55707ee5d44
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column highlights
		dataType: string
		lineageTag: d13e5407-907b-4a90-8b35-c79c68855929
		summarizeBy: none
		sourceColumn: highlights

		annotation SummarizationSetBy = Automatic

	column aggregate_rating
		dataType: double
		lineageTag: 2ed1ec6c-70ce-4377-ab88-dc7519248163
		summarizeBy: sum
		sourceColumn: aggregate_rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rating_text
		dataType: string
		lineageTag: 0cd9d851-e8d7-4569-bb2d-0944be6cb9b8
		summarizeBy: none
		sourceColumn: rating_text

		annotation SummarizationSetBy = Automatic

	column votes
		dataType: int64
		formatString: 0
		lineageTag: 33c6d7d8-94f7-45ef-9374-82ccc38a9269
		summarizeBy: sum
		sourceColumn: votes

		annotation SummarizationSetBy = Automatic

	column photo_count
		dataType: int64
		formatString: 0
		lineageTag: 58eebcf4-4cd9-4b8d-9cb4-3b48ac77ae82
		summarizeBy: sum
		sourceColumn: photo_count

		annotation SummarizationSetBy = Automatic

	column opentable_support
		dataType: int64
		formatString: 0
		lineageTag: 865428f2-f5cf-464c-9be6-ad96c02c861b
		summarizeBy: sum
		sourceColumn: opentable_support

		annotation SummarizationSetBy = Automatic

	column delivery
		dataType: int64
		formatString: 0
		lineageTag: 83e0c5d6-c8c6-4ebc-9bf3-1301d4e8a84e
		summarizeBy: sum
		sourceColumn: delivery

		annotation SummarizationSetBy = Automatic

	column takeaway
		dataType: int64
		formatString: 0
		lineageTag: 58eb13e6-4fe0-4730-90b5-2968e0ca4b9d
		summarizeBy: sum
		sourceColumn: takeaway

		annotation SummarizationSetBy = Automatic

	partition zomato_restaurants_in_India = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\shash\OneDrive\Desktop\powerbi\zomato_restaurants_in_India.csv"),[Delimiter=",", Columns=26, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"res_id", Int64.Type}, {"name", type text}, {"establishment", type text}, {"url", type text}, {"address", type text}, {"city", type text}, {"city_id", Int64.Type}, {"locality", type text}, {"latitude", type number}, {"longitude", type number}, {"zipcode", Int64.Type}, {"country_id", Int64.Type}, {"locality_verbose", type text}, {"cuisines", type text}, {"timings", type text}, {"average_cost_for_two", Int64.Type}, {"price_range", Int64.Type}, {"currency", type text}, {"highlights", type text}, {"aggregate_rating", type number}, {"rating_text", type text}, {"votes", Int64.Type}, {"photo_count", Int64.Type}, {"opentable_support", Int64.Type}, {"delivery", Int64.Type}, {"takeaway", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

