{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IN",
    "cultures": [
      {
        "name": "en-IN",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Table1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Item Fat Content",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58e1d687-024f-41a0-a593-1667ead18e7f",
            "sourceColumn": "Item Fat Content",
            "summarizeBy": "none"
          },
          {
            "name": "Item Identifier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "941d4430-0371-40ee-be34-1ea38144be44",
            "sourceColumn": "Item Identifier",
            "summarizeBy": "none"
          },
          {
            "name": "Item Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dc06afa-657b-4f06-b27f-ac91f2262566",
            "sourceColumn": "Item Type",
            "summarizeBy": "none"
          },
          {
            "name": "Outlet Establishment Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "556d35a3-5a2a-4539-8924-bf643bf671ca",
            "sourceColumn": "Outlet Establishment Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Outlet Identifier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "033a03db-00d8-42f0-b58a-ef4bb5aec22a",
            "sourceColumn": "Outlet Identifier",
            "summarizeBy": "none"
          },
          {
            "name": "Outlet Location Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad5a7009-fac7-4e0a-886b-2f6c835ba438",
            "sourceColumn": "Outlet Location Type",
            "summarizeBy": "none"
          },
          {
            "name": "Outlet Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cc5df34-46e0-4af2-8043-5910317a3853",
            "sourceColumn": "Outlet Size",
            "summarizeBy": "none"
          },
          {
            "name": "Outlet Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cedd419-589a-4d24-b803-39556f81dd64",
            "sourceColumn": "Outlet Type",
            "summarizeBy": "none"
          },
          {
            "name": "Item Visibility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "370bf289-6dcf-4415-91a5-71880243a499",
            "sourceColumn": "Item Visibility",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a4144546-7eae-4f8e-9327-3f4cfb1db6fe",
            "sourceColumn": "Item Weight",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dbd0e69d-9788-4133-9512-860fdc385f6a",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92c37664-194b-4268-b722-c15e3e47022b",
            "sourceColumn": "Rating",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "524ebea9-91f1-4c8f-9b48-bb564456be70",
        "partitions": [
          {
            "name": "Table1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\shash\\Downloads\\BlinkIT Grocery Data.xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"Item Fat Content\", type text}, {\"Item Identifier\", type text}, {\"Item Type\", type text}, {\"Outlet Establishment Year\", Int64.Type}, {\"Outlet Identifier\", type text}, {\"Outlet Location Type\", type text}, {\"Outlet Size\", type text}, {\"Outlet Type\", type text}, {\"Item Visibility\", type number}, {\"Item Weight\", type number}, {\"Sales\", type number}, {\"Rating\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_3832fa0c-aac1-4dfd-bc84-8ee6852b4f5e",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aad49a01-14ee-4e87-b514-e5b35d85a1a9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47292c76-f2aa-4aa1-b276-696165e72ec0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c436fc79-1baf-4290-9dd2-ac3e241f67f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f123e448-4cea-4068-9e32-1fb15a9a1647",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "826b1d61-9ce4-45d9-8321-39b06c1f5c65",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "52834f58-742b-43f5-a6cd-9086d97c3810",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "98c1c55c-de2b-492e-9b22-7357013debf5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "55682c55-71f0-4753-ba39-7ce86879a96c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b579bcb2-99b6-4322-903c-2f34bbb346e3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c1a5aca4-3e0f-4711-9a33-b250c10205a9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7c14dbab-a3b6-4ffd-9287-0aaf5986654b",
                "ordinal": 3
              }
            ],
            "lineageTag": "8e88d393-0dd2-477f-9435-d8e1b7e17797"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1ef77e71-568a-4a54-a9d8-a9d20425baa1",
        "partitions": [
          {
            "name": "DateTableTemplate_3832fa0c-aac1-4dfd-bc84-8ee6852b4f5e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}